package car.model;

/**
 * Companies model for Cargo.
 * 
 * @author Jianqing Ma, Sen Yan, Bo Chen, Bingfan Tian, Qihui Liu, Kailun He
 *
 */
public class Companies {
	protected int companyId;
	protected String companyName;
	protected String Description;
	
	/**
	 * Constructor for reading records from MySQL, where we have all fields, including the companyId.
	 * 
	 * @param companyId The auto-generated and auto-incremented ID for each company.
	 * @param companyName The name of the company.
	 * @param description The description of the company.
	 */
	public Companies(int companyId, String companyName, String description) {
		this.companyId = companyId;
		this.companyName = companyName;
		Description = description;
	}

	/**
	 * Constructor for reading records from MySQL, where we only have the companyId,
	 * such as a foreign key reference to companyId.
	 * Given companyId, we can fetch the full companies record.
	 * 
	 * @param companyId The auto-generated and auto-incremented ID for each company.
	 */
	public Companies(int companyId) {
		super();
		this.companyId = companyId;
	}

	/**
	 * This constructor can be used for creating new records, where the companyId may not be
	 * assigned yet since it is auto-generated by MySQL.
	 * 
	 * @param companyName The name of the company.
	 * @param description The description of the company.
	 */
	public Companies(String companyName, String description) {
		super();
		this.companyName = companyName;
		Description = description;
	}

	/**
	 * The getter for CompanyId.
	 * 
	 * @return companyId for this company.
	 */
	public int getCompanyId() {
		return companyId;
	}

	/**
	 * The setter for the companyId.
	 * 
	 * @param companyId companyId for this company.
	 */
	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	/**
	 * The getter for the name of the company.
	 * 
	 * @return the name of the company.
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * The setter for the company name.
	 * 
	 * @param companyName the name of the company.
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * The description of the company.
	 * 
	 * @return the description of the company.
	 */
	public String getDescription() {
		return Description;
	}

	/**
	 * The setter of the description of the company.
	 * 
	 * @param description the description of the company.
	 */
	public void setDescription(String description) {
		Description = description;
	}
	
}
